name: Build Project

on:
  push:
  workflow_dispatch:

jobs:
  Build:
    strategy:
      matrix:
        java: [ 11, 19 ]
    uses: evanchooly/workflows/.github/workflows/build.yml@master
    with:
      java: ${{ matrix.java }}

  Release:
    needs:
      - Matrix
      - Test
      - CodeAudits
    if: needs.Matrix.outputs.releasable == 'true'
    uses: evanchooly/workflows/.github/workflows/jreleaser.yml@master
    with:
      java: 17
    secrets:
      GH_PUSH_TOKEN       : ${{ secrets.GH_PUSH_TOKEN }}
      GPG_PASSPHRASE      : ${{ secrets.GPG_PASSPHRASE }}
      GPG_PUBLIC_KEY      : ${{ secrets.GPG_PUBLIC_KEY }}
      GPG_PRIVATE_KEY     : ${{ secrets.GPG_PRIVATE_KEY }}
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
